name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    container: 
        image: mmh42/conda-docker-testing:v0.0.1

    steps:
    - uses: actions/checkout@v2
 
    - name: Run pytest with coverage report
      run: |
        which -a python
        which conda
        conda run -n test python -m pytest --cov=./ --cov-report=xml -v test.py
          
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
